import Head from 'next/head';
import Image from 'next/image'
import FlipMove from 'react-flip-move';
import Nav from '../../components/Nav';
import Header from '../../components/Header';

export default function Detail({ detail}) {
    const BASE_URL = "https://image.tmdb.org/t/p/original/";

  return (
    <div>
      <Head>
        <title>Bull 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        {/* Header */}
        <Header />
        {/* Navbar */}
        <Nav />
        {/* Detail */}
       
       <FlipMove className="px-5 my-10 flex flex-wrap justify-center">
            <div className="p-2 ">
               <Image 
                layouts="responsive"
                src={
                    `${BASE_URL}${detail.backdrop_path || detail.poster_path}` ||
                    `${BASE_URL}${detail.poster_path}`
                }
                height={750}
                width={900}
            />

                <div className="p-2">
                    <h2 className="mt-1 text-2xl text-white transition-all duration-100 ease-in-out group-hover:font-bold">{detail.title || detail.original_name}</h2>
                    <p className="max-w-md">{detail.overview}</p>
                    <p className="flex items-center">
                        {detail.media_type && `${detail.media_type} • `}{" "}
                        {detail.release_date || detail.first_air_date}{" "}
                    </p>
                    
                </div>
            </div>
        </FlipMove>
    </div>
  );
}

const API_KEY = process.env.API_KEY;

export async function getServerSideProps(context) {
    const {id} = context.query;
    
    const detail = await fetch(    
        `https://api.themoviedb.org/3/movie/${id}?api_key=${API_KEY}`,
        {
            where: {
                    id: id
                }})
            .then((res) => res.json());
            // console.log(detail);
        
        return {
            props: {
                detail
            },
        }
    }
        