import Head from 'next/head';
import Nav from '../components/Nav';
import Header from '../components/Header';
import Results from '../components/Results';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Bull 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        {/* Header */}
        <Header />

        {/* Navbar */}
        <Nav />
        {/* Result */}
        <Results />

    </div>
  );
}


export async function getServerSideProps(context) {
  const genre = context.query.genre;


}