import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Bull 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1>Le</h1>
    </div>
  );
}
